### ISSUE TITLE
Separate resize-cache folder

### ISSUE THREAD

**Issue by josefzajac** [Carrooi/Nette-ImagesManager#14]
Hi,
not issue, but feature request.
I have 5 years old application with same resize-in-same-folder logic. 
If there is new frontend update for change some resize dimensions/filters, it is not possible to delete all resizes. There are also 5 years old rarely used resizes, can be deleted and used will be generated again.

I will prefer save all thumbnails to cache/$namespace/{maybe year-month}/$thumbnail folder.

Disadvantage is not pretty url, can be solved via script serving cache files with Expire header?
Next advantage of script with expire header is (unusual) usage on cheap public server house services where admin can't configure nginx or apache for static files Expire header setup.
Good is automatic versioning, makes sense with script Expire header setup ;).

**Comment by davidkudera** [comment]
Hello,

I would like to have some kind of `PathResolver`, because everyone can have different preferences about how and where to save their images.

I personally also faced this problem with deprecated or simply old sizes. Current version has one solution, which are [presets](https://github.com/Carrooi/Nette-ImagesManager#presets). This can prevent you from using sizes directly in your templates. Unfortunately this will not work for some old application though...

Expiration is another thing, we need to solve. Again current version changes URL automatically when you upload new image. Something like this: old image was accessed via `image.jpg?v=1`, but new image via `image.jpg?v=2`. So the browser will always load new images when needed, because URL changed. So the expiration can be pretty agresive I think ;-)
